version: 2.1

executors:
  ruby_executor:
    docker:
      # https://hub.docker.com/r/cimg/ruby
      - image: cimg/ruby:<< parameters.version_tag >>
    # resource_class:
    # shell: /bin/sh
    # working_directory: .
    # environment:
    parameters:
      version_tag:
        type: string
        default: 2.7.2

jobs:
  build_by_node:
    docker:
      # https://hub.docker.com/r/cimg/node
      - image: cimg/node:14.15.5
        # name:
        # entrypoint:
        # command:
        # user:
        environment:
          FOO: BAR
          HOGE: FUGA
        # auth:
        # aws_auth:
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Hello, CircleCI cron World on Node image
          command: |
            echo 'Hello, CircleCI cron on cimg/node:14.15.5 !'
      - run:
          name: Show Node.js version
          command: |
            which node
            node --version
            which npm
            npm --version
      - run:
          name: Show Yarn version
          command: |
            which yarn
            yarn --version
      - run:
          name: 各種コマンドの確認
          command: |
            curl --version
            wget --version
            git --version
      - run:
          # Ubuntu 20.04.1
          name: OS情報の確認
          command: |
            cat /etc/issue
            cat /etc/os-release

  build_by_ruby_2_7_2:
    executor:
      name: ruby_executor
      version_tag: 2.7.2
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Hello, CircleCI cron World on Ruby image
          command: |
            echo 'Hello, CircleCI cron World on cimg/ruby:2.7.2 !'
          shell: /bin/sh # デフォルト値（任意項目）
          environment:
            FOO: BAR
          background: false # デフォルト値（任意項目）
          working_directory: . # デフォルト値（任意項目）
          no_output_timeout: 10m # デフォルト値（任意項目）
          when: on_success # デフォルト値（任意項目）
      - run:
          name: Show Ruby version
          command: |
            which ruby
            ruby --version
            which bundler
            bundler --version
      - run:
          name: 各種コマンドの確認
          command: |
            curl --version
            wget --version
            git --version
      - run:
          # Ubuntu 20.04.1
          name: OS情報の確認
          command: |
            cat /etc/issue
            cat /etc/os-release

  build_by_ruby_3_0_0:
    executor:
      name: ruby_executor
      version_tag: 3.0.0
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Hello, CircleCI cron World on Ruby image
          command: |
            echo 'Hello, CircleCI cron World on cimg/ruby:3.0.0 !'
          shell: /bin/sh # デフォルト値（任意項目）
          environment:
            FOO: BAR
          background: false # デフォルト値（任意項目）
          working_directory: . # デフォルト値（任意項目）
          no_output_timeout: 10m # デフォルト値（任意項目）
          when: on_success # デフォルト値（任意項目）
      - run:
          name: Show Ruby version
          command: |
            which ruby
            ruby --version
            which bundler
            bundler --version
      - run:
          name: gh をインストール
          command: |
            wget https://github.com/cli/cli/releases/download/v1.6.2/gh_1.6.2_linux_amd64.deb
            sudo dpkg -i gh_1.6.2_linux_amd64.deb
          shell: /bin/sh # デフォルト値（任意項目）
          environment:
            FOO: BAR
          background: false # デフォルト値（任意項目）
          working_directory: . # デフォルト値（任意項目）
          no_output_timeout: 10m # デフォルト値（任意項目）
          when: on_success # デフォルト値（任意項目）
      - run:
          name: gh のバージョンを確認する
          command: |
            which gh
            $(which gh) --version

  cron:
    docker:
      - image: cimg/ruby:3.0.0
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: echoコマンドで動作確認をする
          command: |
            echo 'Hello, cron用ジョブ！'
          shell: /bin/sh # デフォルト値（任意項目）
          environment:
            CRON: WORLD
          background: false # デフォルト値（任意項目）
          working_directory: . # デフォルト値（任意項目）
          no_output_timeout: 10m # デフォルト値（任意項目）
          when: on_success # デフォルト値（任意項目）
      - run:
          name: Artifacts にファイルを書き出す
          # "destination" が設定されていない場合の store_artifacts 記載のディレクトリは、自前で作らないとダメ
          command: |
            echo 'ハロー、NIFTY SERVER アーティファクト！' > /tmp/my_artifact
            mkdir /tmp/bluemoon
            echo 'ハロー、Bluemoon アーティファクト！' > /tmp/bluemoon/never.txt
      # ログ等を保存する
      - store_artifacts:
          path: /tmp/my_artifact
          # "destination" が指定されている場合は、パス名以降を具体的に指定するとエラーになるので注意する
          destination: nifty_serve
      - store_artifacts:
          # "destination" を指定しない場合には、"path" のディレクトリを自前で mkdir しておかないとエラーになるので注意する
          path: /tmp/bluemoon

  # CLI によるローカルテスト用
  # アーティファクトはサポートされていない（正しい記述なら Success! にはなる）
  # cache機構はサポートされていない（正しい記述なら Success! にはなる）
  build:
    docker:
      - image: cimg/ruby:3.0.0
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: echoコマンドで動作確認をする
          command: |
            echo 'Hello, CircleCI cron World on cimg/ruby:3.0.0 !'
          shell: /bin/sh # デフォルト値（任意項目）
          environment:
            FOO: BAR
          background: false # デフォルト値（任意項目）
          working_directory: . # デフォルト値（任意項目）
          no_output_timeout: 10m # デフォルト値（任意項目）
          when: on_success # デフォルト値（任意項目）
      - run:
          name: Ruby および Bundler のバージョンを確認する
          command: |
            which ruby
            ruby --version
            which bundler
            bundler --version
      - run:
          name: gh をインストールする
          command: |
            wget https://github.com/cli/cli/releases/download/v1.6.2/gh_1.6.2_linux_amd64.deb
            sudo dpkg -i gh_1.6.2_linux_amd64.deb
          shell: /bin/sh # デフォルト値（任意項目）
          environment:
            FOO: BAR
          background: false # デフォルト値（任意項目）
          working_directory: . # デフォルト値（任意項目）
          no_output_timeout: 10m # デフォルト値（任意項目）
          when: on_success # デフォルト値（任意項目）
      - run:
          name: gh のバージョンを確認する
          command: |
            which gh
            $(which gh) --version
      - run:
          name: Artifacts にファイルを書き出す
          command: |
            echo 'ハロー、アーティファクト！' > /tmp/my_artifact
      # ログ等を保存する
      - store_artifacts:
          path: /tmp/my_artifact
          destination: hogefuga

workflows:
  version: 2
  hello_world_by_node_and_ruby:
    jobs:
      - build_by_node
      - build_by_ruby_2_7_2:
          requires:
            - build_by_node
      - build_by_ruby_3_0_0:
          requires:
            - build_by_ruby_2_7_2
      - cron:
          requires:
            - build_by_node
  hello_world_by_node:
    jobs:
      - build_by_node
  hello_world_by_ruby_2_7_2:
    jobs:
      - build_by_ruby_2_7_2
  lets_execute_cron:
    triggers:
      - schedule:
          cron: '10 09 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - cron
  # build を実行する workflow が含まれていないと、CircleCI CLI で実行ができない
  dummy_for_circleci_cli:
    triggers:
      - schedule:
          # 土曜日である 12/24 の 12:30 に実行する（実行を期待していない、ダミーの設定）
          cron: '30 12 24 12 6'
          filters:
            branches:
              only:
                - main
    jobs:
      - build
