version: 2.1

executors:
  ubuntu:
    docker:
      - image: cimg/base:stable-20.04
        environment:
          TZ: "Asia/Tokyo"

jobs:
  hello_world:
    executor: ubuntu
    working_directory: ~/cron_hello_world
    steps:
      - checkout
      - run:
          name: ハローワールド
          command: |
            echo 'Hello, World!'
      - run:
          name: いろいろな which
          command: |
            which curl
            which wget
            which git
            which perl
            which jq
      - run:
          name: OS情報等の確認
          command: |
            echo $SHELL
            cat /etc/issue
            cat /etc/os-release

  good_night_world:
    executor: ubuntu
    working_directory: ~/cron_good_night_world
    steps:
      - checkout
      - run:
          name: グッナイワールド
          command: |
            echo 'Good Night, World!'
          environment:
            FOO: BAR
          background: false
          working_directory: .
          no_output_timeout: 1m
          when: on_success
      - run:
          name: sudo apt update
          command: |
            sudo apt update
      - run:
          name: nodenv を用いて Node.js をインストール
          command: |
            git clone https://github.com/nodenv/nodenv.git ~/.nodenv
            git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build

            export PATH="$HOME/.nodenv/bin:$PATH"
            export PATH="$HOME/.nodenv/shims:$PATH"

            nodenv install 16.10.0
            nodenv global 16.10.0
      - run:
          name: バージョン確認
          command: |
            # 'run' のたびに新しいシェルスクリプトが起動する形なので、毎回環境変数を設定する
            export PATH="$HOME/.nodenv/bin:$PATH"
            export PATH="$HOME/.nodenv/shims:$PATH"

            node --version
            npm --version
      - run:
          name: npm 経由で Yarn をインストールする
          command: |
            # 'run' のたびに新しいシェルスクリプトが起動する形なので、毎回環境変数を設定する
            export PATH="$HOME/.nodenv/bin:$PATH"
            export PATH="$HOME/.nodenv/shims:$PATH"

            npm install -g yarn
            # eval "$(nodenv init -)" を行っていないので、実行ファイルをインストールした後には手動で rehash する必要がある
            nodenv rehash

            yarn --version

  # $ circleci local execute 用（デバッグ用）
  build:
    executor: ubuntu
    working_directory: ~/build_job
    steps:
      - checkout
      - run:
          name: こんにちは
          command: |
            echo 'こんにちは'

workflows:
  version: 2

  cron_hello_world:
    jobs:
      - hello_world
    triggers:
      - schedule:
          # https://circleci.com/docs/ja/2.0/workflows/
          # メモ: cron のステップ構文 (たとえば、*/1、*/20) はサポートされません。 エレメントのカンマ区切りリスト内の範囲エレメントもサポートされません。
          # Docker 内のタイムゾーンに関係なく、+0000 であることに注意する（書かれている日時よりも 9時間後 に実行される）
          cron: '00 03 * * *'
          filters:
            branches:
              only:
                - main
  cron_good_night_world:
    jobs:
      - good_night_world
    triggers:
      - schedule:
          # https://circleci.com/docs/ja/2.0/workflows/
          # メモ: cron のステップ構文 (たとえば、*/1、*/20) はサポートされません。 エレメントのカンマ区切りリスト内の範囲エレメントもサポートされません。
          # Docker 内のタイムゾーンに関係なく、+0000 であることに注意する（書かれている日時よりも 9時間 に実行される）
          cron: '00 04 * * *'
          filters:
            branches:
              only:
                - main
  debug_workflow:
    jobs:
      - good_night_world:
          filters:
            branches:
              only:
                - /circleci-debug.*/
  # $ circleci local execute 用（デバッグ用）
  circleci_cli:
    jobs:
      - build:
          filters:
            branches:
              # CLI 以外で実行するつもりはない
              only:
                - /165b0f1eece480ef28581034ce672a5ac518595f00ac44c45de8c5a738172d49/
