version: 2.1

executors:
  ubuntu:
    docker:
      - image: cimg/base:stable-20.04
        environment:
          TZ: "Asia/Tokyo"

jobs:
  hello_world:
    executor: ubuntu
    working_directory: ~/cron_hello_world
    steps:
      - run:
          name: ハローワールド
          command: |
            echo 'Hello, World!'
      - run:
          name: いろいろな which
          command: |
            which curl
            which wget
            which git
            which php
            which node
            which ruby
            which jq
      - run:
          name: OS情報の確認
          command: |
            cat /etc/issue
            cat /etc/os-release

  good_night_world:
    executor: ubuntu
    working_directory: ~/cron_good_night_world
    steps:
      - run:
          name: グッナイワールド
          command: |
            echo 'Good Night, World!'
          environment:
            FOO: BAR
          background: false
          working_directory: .
          no_output_timeout: 1m
          when: on_success
      - run:
          name: gh のバージョンを確認する
          command: |
            which gh
            $(which gh) --version

workflows:
  version: 2
  cron_hello_world:
    jobs:
      - hello_world
    triggers:
      - schedule:
          # https://circleci.com/docs/ja/2.0/workflows/
          # メモ: cron のステップ構文 (たとえば、*/1、*/20) はサポートされません。 エレメントのカンマ区切りリスト内の範囲エレメントもサポートされません。
          # Docker 内のタイムゾーンに関係なく、+0000 であることに注意する（書かれている日時よりも 9時間 に実行される）
          cron: '10 09 * * *'
          filters:
            branches:
              only:
                - main
  cron_good_night_world:
    jobs:
      - good_night_world
    triggers:
      - schedule:
          # https://circleci.com/docs/ja/2.0/workflows/
          # メモ: cron のステップ構文 (たとえば、*/1、*/20) はサポートされません。 エレメントのカンマ区切りリスト内の範囲エレメントもサポートされません。
          # Docker 内のタイムゾーンに関係なく、+0000 であることに注意する（書かれている日時よりも 9時間 に実行される）
          cron: '15 09 * * *'
          filters:
            branches:
              only:
                - main
