version: 2
jobs:
  build_by_node:
    docker:
      # https://hub.docker.com/r/cimg/node
      - image: cimg/node:14.15.5
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Hello, CircleCI cron World on Node image
          command: |
            echo 'Hello, CircleCI cron on cimg/node:14.15.5 !'
      - run:
          name: Show Node.js version
          command: |
            which node
            node --version
            which npm
            npm --version
      - run:
          name: Show Yarn version
          command: |
            which yarn
            yarn --version
      - run:
          name: 各種コマンドの確認
          command: |
            curl --version
            wget --version
            git --version
      - run:
          # Ubuntu 20.04.1
          name: OS情報の確認
          command: |
            cat /etc/issue
            cat /etc/os-release

  build_by_ruby:
    docker:
      # https://hub.docker.com/r/cimg/ruby
      - image: cimg/ruby:2.7.2
    working_directory: ~/working_directory
    steps:
      - checkout
      - run:
          name: Hello, CircleCI cron World on Ruby image
          command: |
            echo 'Hello, CircleCI cron World on cimg/ruby:2.7.2 !'
          shell: /bin/sh # デフォルト値（任意項目）
          environment:
            FOO: BAR
          background: false # デフォルト値（任意項目）
          working_directory: . # デフォルト値（任意項目）
          no_output_timeout: 10m # デフォルト値（任意項目）
          when: on_success # デフォルト値（任意項目）
      - run:
          name: Show Ruby version
          command: |
            which ruby
            ruby --version
            which bundler
            bundler --version
      - run:
          name: 各種コマンドの確認
          command: |
            curl --version
            wget --version
            git --version
      - run:
          # Ubuntu 20.04.1
          name: OS情報の確認
          command: |
            cat /etc/issue
            cat /etc/os-release

workflows:
  version: 2
  hello_world:
    jobs:
      - build_by_node
      - build_by_ruby
  lets_execute_cron:
    triggers:
      - schedule:
          cron: '10 09 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - build
