name: Renovate
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Renovate を実行する
        # TODO: トークンや設定ファイル、リポジトリ名を DRY にする
        run: |
          docker run --rm -e RENOVATE_TOKEN=${{ secrets.RENOVATE_TOKEN }} -v "renovate.json:/usr/src/app/config.js" renovate/renovate --dry-run=false murasamejo/auto-commit-by-cron-with-circleci

